import type { RimeStyle } from '@/types/rimeStyle.ts';

const defaultStyle: RimeStyle = {
  style: {
    fontFace: '',
    labelFontFace: '',
    commentFontFace: '',
    fontPoint: 12,
    labelFontPoint: 12,
    inlinePreedit: false,
    preeditType: 'composition',
    fullscreen: false,
    verticalText: false,
    candidateListLayout: 'stacked',
    horizontal: false,
    verticalTextLeftToRight: false,
    verticalTextWithWrap: false,
    verticalAutoReverse: false,
    labelFormat: '%s.',
    markText: '|',
    asciiTipFollowCursor: false,
    enhancedPosition: true,
    displayTrayIcon: false,
    antialiasMode: 'default',
    candidateAbbreviationLength: 30,
    pagingOnScroll: true,
    clickToCapture: false,
    layout: {
      baseline: 0,
      linespacing: 0,
      alignType: 'center',
      maxHeight: 600,
      maxWidth: 0,
      minHeight: 0,
      minWidth: 145,
      borderWidth: 2,
      marginX: 10,
      marginY: 10,
      candidateSpacing: 22,
      hiliteSpacing: 6,
      hilitePadding: 8,
      hilitePaddingX: null,
      hilitePaddingY: null,
      shadowRadius: 0,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      cornerRadius: 8,
      roundCorner: 8,
    },
  },
  colorScheme: {
    code: 'code',
    name: 'name',
    author: 'author',
    colorFormat: 'rgba',
    textColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    labelColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    commentTextColor: {
      R: 221,
      G: 221,
      B: 221,
      A: 255,
    },
    borderColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    shadowColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    backColor: {
      R: 255,
      G: 255,
      B: 255,
      A: 255,
    },
    candidateTextColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    candidateBorderColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    candidateBackColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    candidateShadowColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    hilitedTextColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    hilitedLabelColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    hilitedMarkColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    hilitedCommentTextColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    hilitedBackColor: {
      R: 221,
      G: 221,
      B: 221,
      A: 255,
    },
    hilitedShadowColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    hilitedCandidateTextColor: {
      R: 255,
      G: 255,
      B: 255,
      A: 255,
    },
    hilitedCandidateBorderColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    hilitedCandidateBackColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 255,
    },
    hilitedCandidateShadowColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    inlinePreedit: false,
    prevpageColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
    nextpageColor: {
      R: 0,
      G: 0,
      B: 0,
      A: 0,
    },
  },
};

export default defaultStyle;
